---
include:
  - board: ergohaven
    shield: corne_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: ergohaven
    shield: corne_left
    keymap: corne_ruen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: corne_left_ruen-ergohaven-zmk
  - board: ergohaven
    shield: corne_right
  - board: ergohaven
    shield: corne_qube qube dongle_screen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: corne_qube-ergohaven-zmk
  - board: ergohaven
    shield: corne_qube qube dongle_screen
    keymap: corne_ruen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: corne_qube_ruen-ergohaven-zmk
  - board: ergohaven
    shield: corne_left_qube

  - board: ergohaven
    shield: settings_reset
