---
include:

  - board: ergohaven
    shield: corne_left
    keymap: corne_ruen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: corne_left_ruen-ergohaven-zmk
  - board: ergohaven
    shield: corne_right

  - board: ergohaven
    shield: settings_reset
